### ISSUE TITLE
Support for Ubuntu 22.04 (.NET 6)

### ISSUE THREAD

**Issue by Raidenkyu** [MaikelChan/AFSPacker#11]
Hello,

First of all, thanks for all the hard work to make this tool possible.

I was trying to run AFSPacker on Ubuntu 22.04, but unfortunately, I can only install .NET 6, but not .NET Core 3.1, which breaks the compatibility with the last release of AFSPacker. I also tried to clone the repository and build a new executable and run it, but that's the output I got:
```shell
System.ComponentModel.Win32Exception (8): An error occurred trying to start process 'AFSPacker/AFSPacker/bin/Debug/netcoreapp3.1/win-x64/AFSPacker.exe' with working directory 'AFSPacker/AFSPacker'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

Is there any migration for .NET 6 planned? Thanks in advance

Edit: I tried some changes and it did work. I opened a Pull Request https://github.com/MaikelChan/AFSPacker/pull/12 with those changes, so you can take a look

**Comment by MaikelChan** [comment]
As I said in the pull request, sorry for the huge delay, I kind of forgot going back to this. I merged you PR and again, thanks a lot for your contribution.
